export const DEMO_CATEGORIES = [
  {
    parent: {
      name: 'Dama',
      slug: 'dama',
      description: 'Ropa, lencería y accesorios para mujer',
      image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775798805/categories/padre-dama.jpg',
      emoticon: '👗',
      sortOrder: 1,
    },
    subcategories: [
      {
        name: 'Ropa',
        slug: 'dama-ropa',
        description: 'Vestidos, blusas, conjuntos y prendas de mujer',
        image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775798796/categories/dama-ropa.jpg',
        emoticon: '👚',
        sortOrder: 1,
      },
      {
        name: 'Accesorios',
        slug: 'dama-accesorios',
        description: 'Bolsos, carteras y accesorios de moda femenina',
        image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775798791/categories/dama-accesorios.jpg',
        emoticon: '👜',
        sortOrder: 2,
      },
      {
        name: 'Hogar',
        slug: 'dama-hogar',
        description: 'Almohadas, cojines y artículos decorativos para el hogar',
        image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775798793/categories/dama-hogar.jpg',
        emoticon: '🛋️',
        sortOrder: 3,
      },
    ],
  },
  {
    parent: {
      name: 'Bebé',
      slug: 'bebe',
      description: 'Ropa, conjuntos y accesorios para bebé',
      image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775798802/categories/padre-bebe.jpg',
      emoticon: '👶',
      sortOrder: 2,
    },
    subcategories: [
      {
        name: 'Ropa',
        slug: 'bebe-ropa',
        description: 'Onesies, conjuntos y prendas para bebé',
        image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775798790/categories/bebe-ropa.jpg',
        emoticon: '🍼',
        sortOrder: 1,
      },
      {
        name: 'Cobertores',
        slug: 'bebe-cobertores',
        description: 'Cobijas, cobertores y sets de cuna para bebé',
        image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775798787/categories/bebe-cobertores.jpg',
        emoticon: '🧸',
        sortOrder: 2,
      },
      {
        name: 'Accesorios',
        slug: 'bebe-accesorios',
        description: 'Pañaleras, bolsos y accesorios para bebé',
        image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775798784/categories/bebe-accesorios.jpg',
        emoticon: '🎒',
        sortOrder: 3,
      },
      {
        name: 'Gorras',
        slug: 'gorras',
        description: 'Gorras y sombreros para bebé',
        image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775798788/categories/bebe-gorras.jpg',
        emoticon: '🧢',
        sortOrder: 4,
      },
      {
        name: 'Toallas',
        slug: 'bebe-toallas',
        description: 'Toallas con capucha y toallitas para bebé',
        image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775799461/categories/bebe-toallas.jpg',
        emoticon: '🛁',
        sortOrder: 5,
      },
    ],
  },
  {
    parent: {
      name: 'Infantil',
      slug: 'infantil',
      description: 'Ropa y artículos para niños y niñas',
      image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775798807/categories/padre-infantil.jpg',
      emoticon: '🧒',
      sortOrder: 3,
    },
    subcategories: [
      {
        name: 'Ropa',
        slug: 'infantil-ropa',
        description: 'Camisetas, conjuntos y prendas infantiles',
        image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775798800/categories/infantil-ropa.jpg',
        emoticon: '👕',
        sortOrder: 1,
      },
      {
        name: 'Gorras',
        slug: 'infantil-gorras',
        description: 'Gorras y accesorios infantiles',
        image: 'https://res.cloudinary.com/dsr0fsx4v/image/upload/v1775798798/categories/infantil-gorras.jpg',
        emoticon: '🧢',
        sortOrder: 2,
      },
    ],
  },
];
